// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2130.LibraMaster;

import org.usfirst.frc2130.LibraMaster.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton scaleHeightButton;
    public JoystickButton switchHeightButton;
    public JoystickButton intakeHeightButton;
    public JoystickButton disengageBrakeButton;
    public JoystickButton engageBrakeButton;
    public JoystickButton mediumScaleHeightButton;
    public Joystick operatorJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        operatorJoystick = new Joystick(1);
        
        mediumScaleHeightButton = new JoystickButton(operatorJoystick, 1);
        mediumScaleHeightButton.whenPressed(new ElevatorMediumScaleHeight());
        engageBrakeButton = new JoystickButton(operatorJoystick, 10);
        engageBrakeButton.whenPressed(new EngageBrake());
        disengageBrakeButton = new JoystickButton(operatorJoystick, 9);
        disengageBrakeButton.whenPressed(new DisengageBrake());
        intakeHeightButton = new JoystickButton(operatorJoystick, 3);
        intakeHeightButton.whenPressed(new ElevatorIntakeHeight());
        switchHeightButton = new JoystickButton(operatorJoystick, 2);
        switchHeightButton.whenPressed(new ElevatorSwitchHeight());
        scaleHeightButton = new JoystickButton(operatorJoystick, 4);
        scaleHeightButton.whenPressed(new ElevatorScaleHeight());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("ElevatorIntakeHeight", new ElevatorIntakeHeight());
        SmartDashboard.putData("DisengageBrake", new DisengageBrake());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getoperatorJoystick() {
        return operatorJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

