// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2130.driveTrainMet;

import org.usfirst.frc2130.driveTrainMet.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc2130.driveTrainMet.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton driveTrainButton;
    public JoystickButton solFButton;
    public JoystickButton solBButton;
    public JoystickButton solNButton;
    public JoystickButton zeroEncoderButton;
    public JoystickButton enMoveButton;
    public Joystick driveTrainJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        driveTrainJoystick = new Joystick(0);
        
        enMoveButton = new JoystickButton(driveTrainJoystick, 8);
        enMoveButton.whileHeld(new EnMove());
        zeroEncoderButton = new JoystickButton(driveTrainJoystick, 5);
        zeroEncoderButton.whileHeld(new zeroEncoder());
        solNButton = new JoystickButton(driveTrainJoystick, 3);
        solNButton.whileHeld(new solN());
        solBButton = new JoystickButton(driveTrainJoystick, 2);
        solBButton.whileHeld(new solB());
        solFButton = new JoystickButton(driveTrainJoystick, 4);
        solFButton.whileHeld(new solF());
        driveTrainButton = new JoystickButton(driveTrainJoystick, 1);
        driveTrainButton.whileHeld(new runMotor());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("driveTrainCommand", new driveTrainCommand());
        SmartDashboard.putData("runMotor", new runMotor());
        SmartDashboard.putData("solF", new solF());
        SmartDashboard.putData("solB", new solB());
        SmartDashboard.putData("solN", new solN());
        SmartDashboard.putData("EnMove", new EnMove());
        SmartDashboard.putData("zeroEncoder", new zeroEncoder());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getdriveTrainJoystick() {
        return driveTrainJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    
    public boolean driveTrainButtonValue() {
        return driveTrainButton.get();
    }
}

