// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2130.VisionTesting.subsystems;


import org.usfirst.frc2130.VisionTesting.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import com.kauailabs.navx.frc.AHRS;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends Subsystem {

    public double errorPrevious = 0;
    public double limelightX;
    public double limelightY;
    public double limelightArea;


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    private AHRS ahrs;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX lFMotor;
    private WPI_TalonSRX lRMotor;
    private SpeedControllerGroup leftMotors;
    private WPI_TalonSRX rFMotor;
    private WPI_TalonSRX rRMotor;
    private SpeedControllerGroup rightMotors;
    private DifferentialDrive diffDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public DriveTrain() {

        try {
    		ahrs = new AHRS(SPI.Port.kMXP);
    	} catch (RuntimeException ex ) {
    		DriverStation.reportError("Error instantiating navX-MXP" + ex.getMessage(), true);
    	} 

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        lFMotor = new WPI_TalonSRX(1);
        
        
        
        lRMotor = new WPI_TalonSRX(2);
        
        
        
        leftMotors = new SpeedControllerGroup(lFMotor, lRMotor  );
        addChild("LeftMotors",leftMotors);
        
        
        rFMotor = new WPI_TalonSRX(3);
        
        
        
        rRMotor = new WPI_TalonSRX(4);
        
        
        
        rightMotors = new SpeedControllerGroup(rFMotor, rRMotor  );
        addChild("RightMotors",rightMotors);
        
        
        diffDrive = new DifferentialDrive(leftMotors, rightMotors);
        addChild("DiffDrive",diffDrive);
        diffDrive.setSafetyEnabled(true);
        diffDrive.setExpiration(0.1);
        diffDrive.setMaxOutput(1.0);

         

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new AutoCorrecting());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        limelightX = tx.getDouble(0.0);
        limelightY = ty.getDouble(0.0);
        limelightArea = ta.getDouble(0.0);
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public double ahrsAngle() {
        return ahrs.getAngle();
    }

    public void zeroTheSensors() {
        ahrs.reset();
        errorPrevious = 0;
    }

    NetworkTable table = NetworkTableInstance.getDefault().getTable("limelight");
    NetworkTableEntry tx = table.getEntry("tx");
    NetworkTableEntry ty = table.getEntry("ty");
    NetworkTableEntry ta = table.getEntry("ta");


    //post to smart dashboard periodically

    public double controller(double target) {
    	double tolerance = 2; // The robot will try to get within 3 degrees of the desired angle
    	double kP = 0.017; // The proportional gain of our P loop
    	//double kI = 0.0001;
    	double kD = 0.0000197;
    	
    	double dIteration = 0.02;
    	
    	//double iOutput;
    	double dOutput;
    	double error = (target - ahrsAngle());
    	
    	//iGenerator += (error * 0.1);
    	//iOutput = iGenerator * kI;
    	
    	dOutput = (error - errorPrevious) / dIteration;
    	
    	errorPrevious = error;
    	
    	if (Math.abs(error) > tolerance) {
    		return (error * kP) + dOutput * kD; //+ iOutput;
    	} else {
    		return 0.0;
    	}
    }

    public void setWithSaturate(double limitedOutput) {
    	lRMotor.set(limitedOutput);
    	lFMotor.set(limitedOutput);
    	rRMotor.set(limitedOutput);
    	rFMotor.set(limitedOutput);
    }

    public void turnTo(double turnAngle) {
    	setWithSaturate(controller(turnAngle));
    }

}

