// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2130.MomsSpaghetti.subsystems;


import org.usfirst.frc2130.MomsSpaghetti.OI;
import org.usfirst.frc2130.MomsSpaghetti.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import org.usfirst.frc2130.MomsSpaghetti.Robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class driveTrainSub extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX rFMotor;
    private WPI_TalonSRX rRMotor;
    private SpeedControllerGroup speedR;
    private WPI_TalonSRX lFMotor;
    private WPI_TalonSRX lRMotor;
    private SpeedControllerGroup speedL;
    private DifferentialDrive diffDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public driveTrainSub() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rFMotor = new WPI_TalonSRX(3);
        
        
        
        rRMotor = new WPI_TalonSRX(4);
        
        
        
        speedR = new SpeedControllerGroup(rFMotor, rRMotor  );
        addChild("speedR",speedR);
        
        
        lFMotor = new WPI_TalonSRX(1);
        
        
        
        lRMotor = new WPI_TalonSRX(2);
        
        
        
        speedL = new SpeedControllerGroup(lFMotor, lRMotor  );
        addChild("speedL",speedL);
        
        
        diffDrive = new DifferentialDrive(speedL, speedR);
        addChild("diffDrive",diffDrive);
        diffDrive.setSafetyEnabled(true);
        diffDrive.setExpiration(0.1);
        diffDrive.setMaxOutput(1.0);

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new driveTrainCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.



    public void runMotor() {
    lFMotor.set(Robot.oi.driveJoystick.getRawAxis(1));
    lRMotor.set(Robot.oi.driveJoystick.getRawAxis(1));
    rFMotor.set(-Robot.oi.driveJoystick.getRawAxis(1));
    rRMotor.set(-Robot.oi.driveJoystick.getRawAxis(1));
    }
}

